language: python
python:
  - '3.7.3'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="OC_P13_Memory_website.settings.travis"

services:
  - postgresql

script:
  - python manage.py test