# Generated by Django 3.0.8 on 2020-07-16 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recto', models.CharField(max_length=200, verbose_name='recto')),
                ('verso', models.CharField(max_length=200, verbose_name='verso')),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('cards', models.ManyToManyField(to='memory_app.Cards')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0, verbose_name='rank')),
                ('side', models.BooleanField(verbose_name='side')),
                ('cards', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='memory_app.Cards')),
                ('desk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='memory_app.Desk')),
            ],
        ),
    ]
