# Generated by Django 3.0.8 on 2020-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
    ]
